version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
#        networks:
#            - balance
        depends_on:
            - database

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - backend

    database:
        image: 'postgres:14'
        ports:
            - "5432:5432"
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - database-pgsql:/var/lib/postgresql/data
#        networks:
#            - balance
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - .:/var/www

#networks:
#    balance:
#        driver: bridge
volumes:
    database-pgsql:
        driver: local
